### ISSUE TITLE
Apagar retornos anteriores ao utilizar a função "Rodar todos acima"

### ISSUE THREAD

**Issue by paulopha** [thiagocoutinhor/burning-books#36]
No momento em que é utilizado o botão "Rodar todos acima" seria interessante todos  os retornos anteriores ao chunck onde essa função foi utilizada serem instantaneamente removidos.

Isso se mostra útil uma vez que em processos mais longos ,  o tempo de  execução dos blocos superiores podem ser  elevados e o usuário mais desatento pode achar que o novo processo já foi executado, mas o dado exposto ainda é do processo anterior.

**Comment by thiagocoutinhor** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Apagar retornos anteriores ao utilizar a função "Rodar todos acima"](https://trello.com/c/RCtaO8G5/44-apagar-retornos-anteriores-ao-utilizar-a-fun%C3%A7%C3%A3o-rodar-todos-acima)
