### ISSUE TITLE
Exibir o Application_Id ao se connectar

### ISSUE THREAD

**Issue by paulopha** [thiagocoutinhor/burning-books#41]
Seria interessante a exibição do Application_id ao se conectar o notebook, talvez posterior ao botão de conectado.
Isso se mostra util uma vez que é uma atividade corriqueira a checagem da aplicação na spark-ui, checagem de log ou matar o processo , e para isso o application_id é necessário.

**Comment by thiagocoutinhor** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Exibir o Application_Id ao se connectar](https://trello.com/c/7rsnnPaG/48-exibir-o-applicationid-ao-se-connectar)
